@tool
class_name FKSettings
extends Resource
## Stores the core configuration and settings for an RPG project.
## Generated by the Setup tab and used as a reference for all game systems.

## --- Game Profile ---
## Name of the RPG project.
@export var game_name: String = "My RPG"
## FK sub-genre.
@export_enum("Classic JRPG", "Action RPG", "Tactical RPG", "Dungeon Crawler", "Open World", "Autobattler") var genre: String = "Classic JRPG"

## --- Stat System ---
## List of base stat IDs used in this game.
@export var base_stats: Array[String] = ["strength", "dexterity", "intelligence", "wisdom", "vitality", "luck"]
## Derived stats and their formulas. Maps derived_id -> {"weights": {stat_id: multiplier}, "flat": 0.0}.
@export var derived_stats: Dictionary = {}

## --- Element System ---
## List of elements used in this game.
@export var elements: Array[String] = ["Fire", "Ice", "Lightning", "Holy", "Dark"]
## Weakness chart. Maps element -> Array of elements it is strong against.
@export var element_chart: Dictionary = {}

## --- Equipment Slots ---
## List of equipment slot IDs.
@export var equipment_slots: Array[String] = ["main_hand", "off_hand", "head", "body", "legs", "feet", "accessory_1", "accessory_2"]

## --- Economy ---
## Name of the primary currency.
@export var currency_name: String = "Gold"
## Sell-to-buy price ratio (e.g., 0.5 means items sell for half their buy price).
@export var sell_ratio: float = 0.5

## --- Battle System ---
## Battle system type.
@export_enum("Turn-Based", "Active Time Battle", "Autobattle", "Tactical Grid", "Action Real-Time") var battle_type: String = "Turn-Based"
## Maximum party size in battle.
@export var party_size: int = 4
## Maximum enemies per encounter.
@export var max_enemies: int = 4
## How EXP is distributed after battle.
@export_enum("Full to All", "Split Evenly", "Active Only") var exp_distribution: String = "Full to All"
## Can the player flee from normal battles?
@export var allow_flee: bool = true
## Maximum character level.
@export var max_level: int = 99

func _to_string() -> String:
	return game_name
